version: "3.8"

services:
  database:
    image: postgres:15-alpine3.18
    environment:
      - POSTGRES_PASSWORD=rootpw
    ports:
      - "5432:5432"

  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "8010:80"