"""add tags

Revision ID: 64b3a031e667
Revises: 928231a4ee59
Create Date: 2023-06-06 02:40:58.341263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.database import Base

# revision identifiers, used by Alembic.
revision = '64b3a031e667'
down_revision = '928231a4ee59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE tag as ENUM ('all', 'budget', 'paid', 'state', 'nonstate', 'hostel', 'license', 'vuz');")
    op.add_column('university', sa.Column('tags', postgresql.ARRAY(sa.Enum(name='tag')), nullable=True))
    op.drop_column('university', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('university', 'tags')
    # ### end Alembic commands ###
