"""add id to tables

Revision ID: 83a3f2c97e94
Revises: 75b234fcb0b2
Create Date: 2023-06-05 20:09:01.500880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83a3f2c97e94"
down_revision = "75b234fcb0b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
